# Generated by Django 2.1.5 on 2020-04-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageFlipper', '0002_auto_20200418_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipsession',
            name='score_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
