# Generated by Django 2.1.5 on 2020-04-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageFlipper', '0003_auto_20200418_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='score',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, null=True, to='pageFlipper.Profile'),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
