# Generated by Django 2.1.5 on 2020-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageFlipper', '0003_score_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpi',
            name='macAddr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rpi',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
