# Generated by Django 2.1.5 on 2020-04-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageFlipper', '0004_auto_20200418_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipsession',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pageFlipper.Profile'),
        ),
    ]
